[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

# Redirect all requests to the FastAPI app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[dev]
  command = "python -m uvicorn app:app --reload --port 8888"
  port = 8888
  publish = "."